ARG PYTHON_VERSION=latest

FROM python:${PYTHON_VERSION}

WORKDIR /app

COPY . .

RUN python -m pip install -r requirements.txt
RUN python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
RUN python -m nuitka --standalone ./main.py 

CMD ["./main.dist/main.bin"]
