FROM python

WORKDIR /app

COPY . .

RUN python -m pip install -r requirements.txt
RUN python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
RUN python -m nuitka ./main.py 

CMD ["./main.bin"]
