# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/test.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/test.proto\x12\x05proto\"\x1d\n\x07Request\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\tR\x04\x64\x61ta\"\x1e\n\x08Response\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\tR\x04\x64\x61ta2@\n\x0bTestService\x12\x31\n\x0cServerStream\x12\x0e.proto.Request\x1a\x0f.proto.Response0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=27
  _globals['_REQUEST']._serialized_end=56
  _globals['_RESPONSE']._serialized_start=58
  _globals['_RESPONSE']._serialized_end=88
  _globals['_TESTSERVICE']._serialized_start=90
  _globals['_TESTSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
